### ISSUE TITLE
Unfinished sentence in first post

### ISSUE THREAD

**Issue by phil-opp** [TutorialsByNick/tutorialsbynick#2]
In the [Back to Our Code](https://github.com/TutorialsByNick/tutorialsbynick/blob/fe0540058e4adba4b506f56eb0bc2a3a88f5d287/_posts/2016-06-08-writing-an-os-baby-steps.md#back-to-our-code) section:

> - 0x0 in register ah refers to setting the video mode and size. In the second line, we use
> - 0x3 in register al tells int 0x10 that the video size should be 80 characters by 25 characters.

Great post by the way! I'm only halfway through, but I really enjoyed it so far :).

**Comment by nicholasday** [comment]
Thanks Phil! I just removed the unfinished sentence. I don't know what I was doing. :smile:

Let me know how the rest of it goes or if you have any more comments/criticisms.

**Comment by phil-opp** [comment]
Really liking it! No bootloader, just plain assembly interaction with the BIOS. Awesome!

## 

Some minor nits:

> It tells the 0x10 interrupt we use in the loop to allow us to utilize the interrupt for printing characters to the screen.

IMO this sentence is a bit long and difficult to follow.

> The lodsb instruction loads a byte from the segmented address ds:si and moves the si register onto the next byte.

You don't mention into which register the byte is loaded. I assume `al`?

> or al, al performs an or of the al register against itself.

The `al` register is “modified” here but used later. Maybe add a note that `or al, al` doesn't change the value of `al`, but just sets the zero flag.

## 

Very minor:

> `db 'Hello, World!', 13, 10, 0`
> - 10 translates to line feed or \n in ASCII. This moves our cursor to the next lin
> - 13 translates to carriage return or \r in ASCII. This moves our cursor to the start of the line
> - 0 tells our program that this is the end of the string
>   (Thanks @beernuts in the comments for the correction!)
> 
> Both of these values are legacies left over from teletypewriters

In your code, 13 comes before 10. However, you explain it the other way round. And which two do you mean with “both”? `\r` and `\n`?

**Comment by nicholasday** [comment]
Thanks Phil! I believe I fixed all of your edits.

I want to continue the series by making it into a bootloader by using more BIOS interrupts and assembly while explaining more about how the computer boots up.

**Comment by phil-opp** [comment]
Sounds great! I'm looking forward to it.
